# Generated by Django 4.2.6 on 2023-12-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('std_code', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=13)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudops.language')),
            ],
        ),
    ]
